# Site settings
title: Systems Notes
email: jake.waksbaum@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My notes from Systems Level Programming (MKS43C), in beautiful markdowny
  syntax-highlighty latexy goodnes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username: jbaum98
exclude: [ .jekyll ]

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
